export enum CONVERSATION_ACTION_TYPES {
  SET_CONVERSATION = "conversation/SET_CONVERSATION",
  FETCH_CONVERSATION_START = "conversation/FETCH_CONVERSATION_START",
  FETCH_CONVERSATION_SUCCESS = "conversation/FETCH_CONVERSATION_SUCCESS",
  FETCH_CONVERSATION_FAILED = "conversation/FETCH_CONVERSATION_FAILED",
  FETCH_CONVERSATIONS_START = "conversation/FETCH_CONVERSATIONS_START",
  FETCH_CONVERSATIONS_SUCCESS = "conversation/FETCH_CONVERSATIONS_SUCCESS",
  FETCH_CONVERSATIONS_FAILED = "conversation/FETCH_CONVERSATIONS_FAILED",
  SEND_MESSAGE_START = "conversation/SEND_MESSAGE_START",
  SEND_MESSAGE_SUCCESS = "conversation/SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_FAILED = "conversation/SEND_MESSAGE_FAILED",
  RESET_CONVERSATION = "conversation/RESET_CONVERSATION",
}
