export const PRODUCTS_LIST_PAGINATION_ACTION_TYPES = {
  SET_PRODUCTS: "productsListPagination/SET_PRODUCTS",
  SET_PAGE_NUMBER:"productsListPagination/SET_PAGE_NUMBER",
  SET_PAGE_SIZE:"productsListPagination/SET_PAGE_SIZE",
  FETCH_PRODUCTS_START: "productsListPagination/FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "productsListPagination/FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "productsListPagination/FETCH_PRODUCTS_FAILED",
  INCREMENT_PAGE:"productsListPagination/INCREMENT_PAGE",
  DECREMENT_PAGE:"productsListPagination/DECREMENT_PAGE",
};